### ISSUE TITLE
communication/work problem

### ISSUE THREAD

**Issue by VojislavM** [IRNAS/Koruza-Move-Driver-Firmware#13]
When first connected to the Koruza CM board, with fresh firmware, Koruza move driver boards are working fine. Problem occurs when CM reboot, and after that the communication is dead or something else happens. Move driver do not work anymore. When move driver is used with PC serial bridge, then it works every time. 
Possible issues could be:
* the move driver oscillators is bad
* the move driver power supply 3V3 is bad
* the CM 9V power supply is bad
* move driver firmware problem
* Koruza CM software problem

**Comment by VojislavM** [comment]
The problem was in the communication **handshake** and **firmware code**.

The problem with a handshake was that CM was sending "restore motor position" TLV command at the beginning to move driver. The new move driver, based on the ATmega328p does not need "restore motor position" command because it has an EEPROM where it saves positions.

The problem with the firmware was that "restore motor position was not implemented, and error in the code caused the driver to overflow the memory because it did not free the current message.

Barcelona, 24.02.2017.

**Comment by kostko** [comment]
> The problem with the firmware was that "restore motor position was not implemented, and error in the code caused the driver to overflow the memory because it did not free the current message.

This sounds dangerous, please add some tests where the firmware is given invalid messages and ensure that it doesn't crash while processing those (e.g. they should just be discarded).

**Comment by VojislavM** [comment]
Yes, I fixed that, invalid messages are now discarded. But I will write some tests too.
