### ISSUE TITLE
strange problem when when going to minus

### ISSUE THREAD

**Issue by VojislavM** [IRNAS/Koruza-Move-Driver-Firmware#18]
Strange problem is occurring when arrow for down is pressed in the web interface, coordinates move, but not the motor (camera does not move). But when homing is called the motor moves in both directions....

**Comment by SloMusti** [comment]
If this was a homing switch problem, then I would expect the homing to fail as well.

**Comment by VojislavM** [comment]
yes, I just tested if the sw was broken, and pressed all the time, motor would not move, but the coordinate will also stay the same in the web gui...

**Comment by VojislavM** [comment]
mechanical issue
